apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster-a
  namespace: kafka-test
  labels:
    acs.amadeus.com/securityZone: app
spec:
  entityOperator:
    topicOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    jvmOptions:
      '-Xms': 4g
      '-Xmx': 4g
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    replicas: 2
    resources:
      limits:
        cpu: 1
        memory: 6Gi
      requests:
        cpu: 1
        memory: 6Gi
    storage:
      type: ephemeral
    version: 2.5.1
  zookeeper:
    jvmOptions:
      '-Xms': 1g
      '-Xmx': 1g
    replicas: 1
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    storage:
      type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster-b
  namespace: kafka-test
  labels:
    acs.amadeus.com/securityZone: app
spec:
  entityOperator:
    topicOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    jvmOptions:
      '-Xms': 4g
      '-Xmx': 4g
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    replicas: 2
    resources:
      limits:
        cpu: 1
        memory: 6Gi
      requests:
        cpu: 1
        memory: 6Gi
    storage:
      type: ephemeral
    version: 2.5.1
  zookeeper:
    jvmOptions:
      '-Xms': 1g
      '-Xmx': 1g
    replicas: 1
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    storage:
      type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka-test
  labels:
    strimzi.io/cluster: my-cluster-a
spec:
  partitions: 1
  replicas: 1
