apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  namespace: kafka-test
spec:
  clusters:
    - alias: mirror1-cluster
      bootstrapServers: 'my-cluster-a-kafka-bootstrap.kafka-test.svc.cluster.local:9092'
    - alias: mirror2-cluster
      bootstrapServers: 'my-cluster-b-kafka-bootstrap.kafka-test.svc.cluster.local:9092'
      config:
        config.storage.replication.factor: 1
#        config.storage.topic: mm2-configs.my-cluster-a.internal
        offset.storage.replication.factor: 1
#        offset.storage.topic: mm2-offsets.my-cluster-a.internal
        status.storage.replication.factor: 1
#        status.storage.topic: mm2-status.my-cluster-a.internal
  connectCluster: mirror2-cluster
#  resources:
#    requests:
#      cpu: 500m
#      memory: 0.5Gi
#    limits:
#      cpu: 500m
#      memory: 0.5Gi
  logging:
    loggers:
      connect.root.logger.level: DEBUG
    type: inline
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
          emit.checkpoints.enabled: true
          emit.checkpoints.interval.seconds: 10
          refresh.groups.enabled: true
          refresh.groups.interval.seconds: 10
          sync.group.offsets.enabled: true
          sync.group.offsets.interval.seconds: 10
      groupsPattern: .*
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      sourceCluster: mirror1-cluster
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 1
          refresh.topics.enabled: true
          replication.factor: 1
          sync.topic.configs.enabled: true
          tasks.max: 2
      targetCluster: mirror2-cluster
      topicsPattern: .*
  replicas: 1
  version: 2.7.0
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "DEBUG"
  