apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  namespace: kafka-test
  labels:
    acs.amadeus.com/securityZone: app
spec:
  clusters:
    - alias: mirror1-cluster
      bootstrapServers: 'my-cluster-a-kafka-bootstrap.kafka-test.svc.cluster.local:9092'
    - alias: mirror2-cluster
      bootstrapServers: 'my-cluster-b-kafka-bootstrap.kafka-test.svc.cluster.local:9092'
      config:
        config.storage.replication.factor: 1
#        config.storage.topic: mm2-configs.my-cluster-a.internal
        offset.storage.replication.factor: 1
#        offset.storage.topic: mm2-offsets.my-cluster-a.internal
        status.storage.replication.factor: 1
#        status.storage.topic: mm2-status.my-cluster-a.internal
  connectCluster: mirror2-cluster
  resources:
    requests:
      cpu: 500m
      memory: 0.5Gi
    limits:
      cpu: 500m
      memory: 0.5Gi
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 2
          emit.checkpoints.enabled: true
          emit.checkpoints.interval.seconds: 10
          refresh.groups.enabled: true
          refresh.groups.interval.seconds: 10
          sync.group.offsets.enabled: true
          sync.group.offsets.interval.seconds: 10
      groupsPattern: .*
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 2
      sourceCluster: mirror1-cluster
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 2
          refresh.topics.enabled: true
          replication.factor: 2
          sync.topic.configs.enabled: true
          tasks.max: 2
      targetCluster: mirror2-cluster
      topicsPattern: .*
  replicas: 1
  version: 2.5.1
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "DEBUG"
  