apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka #1
  namespace: kafka-dcs
spec:
  kafka:
    version: 2.7.0 #2
    replicas: 1 #3
    resources: #4
      requests:
        memory: 1Gi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 500m
    listeners: #6
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config: #7
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
      log.retention.hours: 1
    storage: #8
      type: ephemeral
    logging: #9
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
  zookeeper: #10
    replicas: 1
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 0.5Gi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
  entityOperator: #11
    topicOperator: {}
    userOperator: {}