apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster-a
  namespace: kafka-test
spec:
  entityOperator:
    topicOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
#    jvmOptions:
#      '-Xms': 2g
#      '-Xmx': 2g
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    replicas: 2
 #   resources:
 #     limits:
 #       cpu: 500m
 #       memory: 1Gi
 #     requests:
 #       cpu: 250m
 #       memory: 0.5Gi
    storage:
      type: ephemeral
    version: 2.7.0
  zookeeper:
#    jvmOptions:
#      '-Xms': 1g
#      '-Xmx': 1g
    replicas: 1
#    resources:
#      limits:
#        cpu: 500m
#        memory: 1Gi
#      requests:
#        cpu: 250m
#        memory: 0.5Gi
    storage:
      type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster-b
  namespace: kafka-test
  labels:
    acs.amadeus.com/securityZone: app
spec:
  entityOperator:
    topicOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
 #   jvmOptions:
 #     '-Xms': 2g
 #     '-Xmx': 2g
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    replicas: 2
 #   resources:
 #     limits:
 #       cpu: 1
 #       memory: 4Gi
 #     requests:
 #       cpu: 1
 #       memory: 4Gi
    storage:
      type: ephemeral
    version: 2.7.0
  zookeeper:
#    jvmOptions:
#      '-Xms': 1g
#      '-Xmx': 1g
    replicas: 1
#    resources:
#      limits:
#        cpu: 1
#        memory: 2Gi
#      requests:
#        cpu: 1
#        memory: 2Gi
    storage:
      type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka-test
  labels:
    strimzi.io/cluster: my-cluster-a
spec:
  partitions: 1
  replicas: 1
