kubectl apply -f 010-ServiceAccount-strimzi-cluster-operator.yaml
kubectl apply -f 020-ClusterRole-strimzi-cluster-operator-role.yaml
kubectl apply -f 020-RoleBinding-strimzi-cluster-operator.yaml
kubectl apply -f 021-ClusterRole-strimzi-cluster-operator-role.yaml
kubectl apply -f 021-ClusterRoleBinding-strimzi-cluster-operator.yaml
kubectl apply -f 030-ClusterRole-strimzi-kafka-broker.yaml
kubectl apply -f 030-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml
kubectl apply -f 031-ClusterRole-strimzi-entity-operator.yaml
kubectl apply -f 031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml
kubectl apply -f 032-ClusterRole-strimzi-topic-operator.yaml
kubectl apply -f 032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml
kubectl apply -f 033-ClusterRole-strimzi-kafka-client.yaml
kubectl apply -f 033-ClusterRoleBinding-strimzi-cluster-operator-kafka-client-delegation.yaml
kubectl apply -f 042-Crd-kafkaconnects2i.yaml
kubectl apply -f 043-Crd-kafkatopic.yaml
kubectl apply -f 044-Crd-kafkauser.yaml
kubectl apply -f 045-Crd-kafkamirrormaker.yaml
kubectl apply -f 046-Crd-kafkabridge.yaml
kubectl apply -f 047-Crd-kafkaconnector.yaml
kubectl apply -f 040-Crd-kafka.yaml
kubectl apply -f 041-Crd-kafkaconnect.yaml
kubectl apply -f 048-Crd-kafkamirrormaker2.yaml
kubectl apply -f 049-Crd-kafkarebalance.yaml
kubectl apply -f 050-ConfigMap-strimzi-cluster-operator.yaml
kubectl apply -f 060-Deployment-strimzi-cluster-operator.yaml